apply from: "$rootDir/buildLogic.gradle"
apply from: "$rootDir/testLogic.gradle"
apply from: "$rootDir/publishLogic.gradle"

dependencies {
    api libs.commons.io
    api libs.commons.lang
    api libs.log4j.core
    testImplementation libs.testng
}

def generateSpecificationVersionFileTask = tasks.register('generateSpecificationVersionFile') {
    def version = objects.property(String)
            .convention(version)
    def specificationVersionFile = objects.fileProperty()
            .convention(layout.buildDirectory.file('specification-version.txt'))
    inputs.property 'version', version
    outputs.file specificationVersionFile
    doLast {
        specificationVersionFile.get().asFile.text = version.get()
    }
}

processResources {
    from generateSpecificationVersionFileTask, {
        into 'marytts'
    }
}

test {
    useTestNG()
    systemProperty 'version', version
}
